<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<form action="" class="row">
    <div class="col-auto mb-1">

        <select class="form-select" style="border-radius: 40px;" name="sort_order"
            aria-label="<?php echo $translate('Sort order'); ?>">
            <option value="asc" <?php echo ($sortOrderQuery === 'asc') ? 'selected' : ''; ?>><?php echo $translate('Ascending'); ?>
            </option>
            <option value="desc" <?php echo ($sortOrderQuery === 'desc') ? 'selected' : ''; ?>><?php echo $translate('Descending'); ?>
            </option>
        </select>
    </div>
    <div class="col-auto mb-1">
        <button type="submit" style="border-radius: 40px;" class="btn btn-outline-primary"><?php echo $translate('Sort'); ?></button>
    </div>

</form>